using System.Collections.Concurrent;

namespace Dali.Metadata;

/// <summary>
/// Generic metadata interface for a document type.
/// </summary>
public interface ITypeMetadata
{
    /// <summary>
    /// The snake_case table name for this document type.
    /// </summary>
    string TableName { get; }

    /// <summary>
    /// Whether this document type has a TenantId string property.
    /// </summary>
    bool HasTenantId { get; }

    /// <summary>
    /// Whether this document type has a version field (via <see cref="IVersioned"/> or <see cref="VersionAttribute"/>).
    /// </summary>
    bool HasVersion { get; }

    /// <summary>
    /// The name of the version property, or null if this type has no version field.
    /// Generated metadata provides this directly from compile-time analysis, avoiding reflection.
    /// </summary>
    string? VersionFieldName { get; }
}

/// <summary>
/// Typed metadata interface for a specific document type T.
/// Generated metadata classes implement this interface.
/// </summary>
public interface ITypeMetadata<T> : ITypeMetadata
{
    /// <summary>
    /// Gets the tenant ID from the entity, or null if not tenant-aware.
    /// </summary>
    string? GetTenantId(T entity);

    /// <summary>
    /// Gets the current version from the entity, or -1 if no version field.
    /// </summary>
    long GetVersion(T entity);

    /// <summary>
    /// Sets the version on the entity (increments it).
    /// </summary>
    void SetVersion(T entity, long version);

    /// <summary>
    /// Extracts the string record ID from the entity's Id property.
    /// Handles <see cref="SurrealDb.Net.Models.RecordIdOf{T}"/> types.
    /// </summary>
    string? GetRecordId(T entity);
}

/// <summary>
/// Central registry for per-type metadata generated by the Dali source generator.
/// Generated <c>{Type}Metadata</c> classes self-register in their static constructors.
/// Runtime code queries the registry to avoid reflection in hot paths.
/// </summary>
public static class MetadataRegistry
{
    private static readonly ConcurrentDictionary<Type, ITypeMetadata> _cache = new();

    /// <summary>
    /// Called by generated code to register metadata for a type.
    /// Thread-safe; intended to be called from static constructors during assembly load.
    /// </summary>
    public static void Register<T>(ITypeMetadata<T> metadata)
    {
        _cache[typeof(T)] = metadata;
    }

    /// <summary>
    /// Attempts to retrieve metadata for the given type.
    /// Returns null if no metadata has been registered (e.g., the type is not a Record subclass).
    /// </summary>
    public static ITypeMetadata? TryGet(Type type)
    {
        _cache.TryGetValue(type, out var metadata);
        return metadata;
    }

    /// <summary>
    /// Gets the metadata for type T, or null if not registered.
    /// </summary>
    public static ITypeMetadata<T>? TryGet<T>()
    {
        if (_cache.TryGetValue(typeof(T), out var metadata) && metadata is ITypeMetadata<T> typed)
            return typed;
        return null;
    }
}
