using System.Collections.Concurrent;

namespace AeroDB.Sable.Metadata;

/// <summary>
/// Compile-time schema for a document property, emitted by the AeroDB.Sable source generator.
/// Used by <c>SchemaManager</c> to emit DEFINE FIELD statements without reflection.
/// </summary>
public readonly record struct FieldSchema(
    string Name,
    string SurrealType,
    bool CanRead,
    bool CanWrite)
{
    /// <summary>
    /// Whether this object-shaped field admits undeclared nested properties while
    /// its containing table remains SCHEMAFULL.
    /// </summary>
    public bool IsFlexible { get; init; }

    /// <summary>The reversible encryption algorithm, or null for a clear field.</summary>
    public EncryptionAlgorithm? EncryptionAlgorithm { get; init; }
}

/// <summary>
/// Generated or fluent runtime access to one encrypted domain property.
/// </summary>
public sealed record EncryptedFieldDescriptor(
    string PropertyName,
    Type ClrType,
    string CodecId,
    EncryptionAlgorithm Algorithm,
    Func<object, object?> GetValue,
    Action<object, object?> SetValue);

/// <summary>Generated or fluent runtime metadata for one blind-indexed field.</summary>
public sealed record BlindIndexDescriptor(
    string PropertyName,
    BlindIndexAlgorithm Algorithm,
    BlindIndexNormalizer Normalizer,
    string? StorageFieldName,
    Func<object, string?> GetValue);

/// <summary>
/// Generic metadata interface for a document type.
/// </summary>
public interface ITypeMetadata
{
    /// <summary>
    /// The snake_case table name for this document type.
    /// </summary>
    string TableName { get; }

    /// <summary>
    /// Whether this document type has a TenantId string property.
    /// </summary>
    bool HasTenantId { get; }

    /// <summary>
    /// Whether this document type has a version field (via <see cref="IVersioned"/> or <see cref="VersionAttribute"/>).
    /// </summary>
    bool HasVersion { get; }

    /// <summary>
    /// Whether this document type implements <see cref="IDocumentMetadata"/> for auto-tracked
    /// audit timestamps (CreatedAt, LastModified).
    /// </summary>
    bool HasDocumentMetadata { get; }

    /// <summary>
    /// Whether this document type has an associated <see cref="EventProjection{T}"/> dispatch.
    /// When true, the source generator has emitted (or can emit) a type-switch ApplyEvents override
    /// for the projection class, avoiding runtime reflection.
    /// </summary>
    bool HasEventProjectionDispatch { get; }

    /// <summary>
    /// The name of the version property, or null if this type has no version field.
    /// Generated metadata provides this directly from compile-time analysis, avoiding reflection.
    /// </summary>
    string? VersionFieldName { get; }

    /// <summary>Untyped version accessor delegate for generated types. Null if no version field.</summary>
    Func<object, long>? GetVersionAccessor { get; }

    /// <summary>Untyped version setter delegate for generated types. Null if no version field.</summary>
    Action<object, long>? SetVersionAccessor { get; }

    /// <summary>Untyped record ID accessor delegate for generated types. Null if no Id property.</summary>
    Func<object, string?>? GetRecordIdAccessor { get; }

    /// <summary>
    /// Compile-time list of public readable/writable properties (excluding Id).
    /// Emitted by the source generator; null when metadata is generated by a legacy
    /// source generator that predates field schema support.
    /// </summary>
    IReadOnlyList<FieldSchema>? Fields { get; }

    /// <summary>Source-generated encrypted-property accessors for this type.</summary>
    IReadOnlyList<EncryptedFieldDescriptor>? EncryptedFields { get; }

    /// <summary>Source-generated blind-index accessors for this type.</summary>
    IReadOnlyList<BlindIndexDescriptor>? BlindIndexes => null;
}

/// <summary>
/// Typed metadata interface for a specific document type T.
/// Generated metadata classes implement this interface.
/// </summary>
public interface ITypeMetadata<T> : ITypeMetadata
{
    /// <summary>
    /// Gets the tenant ID from the entity, or null if not tenant-aware.
    /// </summary>
    string? GetTenantId(T entity);

    /// <summary>
    /// Gets the current version from the entity, or -1 if no version field.
    /// </summary>
    long GetVersion(T entity);

    /// <summary>
    /// Sets the version on the entity (increments it).
    /// </summary>
    void SetVersion(T entity, long version);

    /// <summary>
    /// Extracts the string record ID from the entity's Id property.
    /// Handles <see cref="SurrealDb.Net.Models.RecordIdOf{T}"/> types.
    /// </summary>
    string? GetRecordId(T entity);

    /// <summary>Sets the tenant ID on the entity, or no-op if not tenant-aware.</summary>
    void SetTenantId(T entity, string? tenantId);
}

/// <summary>
/// Central registry for per-type metadata generated by the AeroDB.Sable source generator.
/// Generated <c>{Type}Metadata</c> classes self-register in their static constructors.
/// Runtime code queries the registry to avoid reflection in hot paths.
/// </summary>
public static class MetadataRegistry
{
    private static readonly ConcurrentDictionary<Type, ITypeMetadata> _cache = new();
    private static readonly ConcurrentBag<RelationshipCandidate> _relationshipCandidates = new();

    /// <summary>
    /// Called by generated code to register metadata for a type.
    /// Thread-safe; intended to be called from static constructors during assembly load.
    /// </summary>
    public static void Register<T>(ITypeMetadata<T> metadata)
    {
        _cache[typeof(T)] = metadata;
    }

    /// <summary>
    /// Attempts to retrieve metadata for the given type.
    /// Returns null if no metadata has been registered (e.g., the type is not a Record subclass).
    /// </summary>
    public static ITypeMetadata? TryGet(Type type)
    {
        _cache.TryGetValue(type, out var metadata);
        return metadata;
    }

    /// <summary>
    /// Gets the metadata for type T, or null if not registered.
    /// </summary>
    public static ITypeMetadata<T>? TryGet<T>()
    {
        if (_cache.TryGetValue(typeof(T), out var metadata) && metadata is ITypeMetadata<T> typed)
            return typed;
        return null;
    }

    /// <summary>
    /// Called by generated code to register compile-time relationship candidates.
    /// These candidates are shape-only hints; <see cref="SchemaOptions"/> remains
    /// the runtime authority that applies naming policy, table names, and overrides.
    /// </summary>
    public static void RegisterRelationshipCandidates(params RelationshipCandidate[] candidates)
    {
        foreach (var candidate in candidates)
            _relationshipCandidates.Add(candidate);
    }

    internal static IReadOnlyList<RelationshipCandidate> RelationshipCandidates => _relationshipCandidates.ToArray();

    // Shim type lookup for IEntity<TId> CBOR deserialization
    private static readonly ConcurrentDictionary<Type, Type> _shimTypes = new();

    /// <summary>
    /// Registers a shim type for an IEntity{TId} type.
    /// Called by generated shim static constructors.
    /// </summary>
    public static void RegisterShimType<TEntity>(Type shimType)
    {
        _shimTypes[typeof(TEntity)] = shimType;
    }

    /// <summary>
    /// Gets the registered shim type for the given entity type, or null if none.
    /// </summary>
    public static Type? GetShimType(Type entityType)
    {
        _shimTypes.TryGetValue(entityType, out var shimType);
        return shimType;
    }
}
