<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestModels.fs" />
    <Compile Include="TestHarness.fs" />
    <Compile Include="SableQueryTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SurrealDb.Embedded.InMemory" Version="0.10.2" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="TUnit" Version="1.58.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AeroDB.Sable.FSharp\AeroDB.Sable.FSharp.fsproj" />
  </ItemGroup>
</Project>
