<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>AeroDB.Reactive</PackageId>
    <Description>Reactive Extensions for AeroDB live queries</Description>
    <PackageTags>AeroDB SurrealDB Reactive Extensions LiveQuery</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroDB\AeroDB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

</Project>
