namespace AeroDB;

/// <summary>
/// Compares expected schema (from DocumentMapping) against actual database state.
/// Generated by <see cref="SchemaDiffer"/>.
/// </summary>
public class SchemaDiff
{
    /// <summary>A single difference between expected and actual schema.</summary>
    public record DiffEntry(string Table, string Item, string Expected, string Actual, string Message);

    /// <summary>All detected differences.</summary>
    public List<DiffEntry> Differences { get; } = new();

    /// <summary>Whether any differences were found.</summary>
    public bool HasChanges => Differences.Count > 0;
}
