<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>AeroDB.Sable.Configuration</PackageId>
    <Description>Encrypted .NET configuration provider backed by embedded SurrealDB SurrealKV</Description>
    <PackageTags>surrealdb configuration encryption surrealkv</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroDB.Sable\AeroDB.Sable.csproj" />
    <ProjectReference Include="..\..\surrealdb.net\SurrealDb.Net\SurrealDb.Net.csproj" />
    <ProjectReference Include="..\..\surrealdb.net\SurrealDb.Embedded.SurrealKv\SurrealDb.Embedded.SurrealKv.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dahomey.Cbor" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" VersionOverride="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="../../README.md" />
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
